name: Python CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.18"
          cache: pip  
          
      - run: python -m pip install -r requirements.txt
      - run: pytest
